apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/basic-go/base
- components/basic-quarkus/base
- components/dotnet60-sample/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
